### ISSUE TITLE
Remaining code cleanup - Use of f.erase!

### ISSUE THREAD

**Issue by johnwmcc** [SketchUp/sketchup-shapes#13]
L514:

``` ruby
inner[0].faces.each { |f| f.erase! if(f != face) }
```

You commented earlier: 
"Is this (f.erase!) safe? Erasing from the collection it iterates might 
  be problematic. It's normally safer to collect entities to erase and bulk
  erase them after iterating. It's also faster to erase in bulk than individual entities"

That may be so, but I don't know how to do that. I don't really even know what this line is doing - how can you erase a 'face' that isn't a face?

And because there are so few faces, I doubt if speed matters.

**Comment by DanRathbun** [comment]
**Just an FYI, as to why this was failing.**

```text
Error: #<SyntaxError: D:/Documents/GitHub/my-sketchup-shapes/src/su_shapes/shapes.rb:515: 
syntax error, unexpected '}', expecting keyword_then or ';' or '\n'
```
```ruby
  faces = inner[0].faces.select { |f| if f != face}
```

If you read the error message, it says it was expecting a "`then`" keyword, which implies it also expected a **statement**.

**WHY?** Because you left the "`if`" inside the block, when you changed the code to use `select`. This method and others like `any?`, `find` and `find_all` only need a block that evaluates to boolean `TRUE` or `FALSE`.

So simply the expression `f != face` or `f != outer_face` will evaluate boolean and satisfy the `select` method's internal test when the `yield` from the block returns upon each iteration. The fix was:
```ruby
  faces = inner[0].faces.select { |f| f != face }
```
or
```ruby
  faces = inner[0].faces.select { |f| f != outer_face }
```
... depending upon what the preceding reference name to the outer face was in the code.

**Comment by johnwmcc** [comment]
Thanks, Dan. At least I now understand what was going on then, which I certainly didn't at the time!
